# Generated by Django 2.2.8 on 2021-05-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0002_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('category', models.CharField(choices=[('Health', 'Health'), ('Studies', 'Studies'), ('Grocery', 'Grocery'), ('Belongings', 'Belongings')], max_length=50)),
            ],
        ),
    ]
