# Generated by Django 2.2.8 on 2021-06-14 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0004_auto_20210614_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
    ]
