# Generated by Django 2.2.8 on 2021-06-18 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0005_auto_20210614_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SelF.Profile'),
        ),
    ]
