# Generated by Django 2.2.8 on 2021-06-18 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0006_attendance_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
