# Generated by Django 2.2.8 on 2021-06-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0007_auto_20210618_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance',
            field=models.FloatField(null=True),
        ),
    ]
