# Generated by Django 2.2.8 on 2021-06-20 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SelF', '0008_attendance_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='income',
        ),
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='item',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='userProfile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Studies', 'Studies'), ('Grocery', 'Grocery'), ('Belongings', 'Belongings')], max_length=50, null=True),
        ),
    ]
