# Generated by Django 2.2.8 on 2021-06-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0009_auto_20210620_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Health', 'Health'), ('Education', 'Education'), ('Food', 'Food'), ('Personal', 'Personal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
