# Generated by Django 2.2.8 on 2021-06-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0011_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='creditsEarned',
            field=models.FloatField(null=True),
        ),
    ]
