# Generated by Django 2.2.8 on 2021-06-30 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0013_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='University',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
