# Generated by Django 2.2.8 on 2021-06-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0015_auto_20210630_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
