# Generated by Django 2.2.8 on 2021-07-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelF', '0016_remove_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
